server:
  port: 7001

#Eureka
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false # 是否注册自己
    fetch-registry: false # false: 表示为注册中心
    service-url: # 监控页面
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/