server:
  port: 3344

spring:
  application:
    name: springcloud-config-server
  # 连接仓库
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/liang-jianguo/springcloud-config.git #https 不是git